### ISSUE TITLE
Begrippenkader i.p.v. Woordenboek

### ISSUE THREAD

**Issue by mickbaggen** [nl-digigo/kadersinformatiemodellen#2]
Om goed aan te sluiten bij de NL-SBB, Standaard voor het beschrijven van begrippen, is het minder verwarrend om de term "Begrippenkader" (of vocabulaire) te gebruiken i.p.v. de term "Woordenboek". 

In par. 3.2. wordt dit ook wel gezegd ("Voor het opstellen van een woordenboek passen we de SBB toe. Daarbij voegen we eigen richtlijnen toe; dit geven we dan ook aan. Deze richtlijnen kunnen worden gezien als een toepassingsprofiel op de SBB."), maar het is nu erg onduidelijk wat een kopie is van SBB, wat een eigen richtlijn, en waarom er nu eigen richtlijnen nodig zijn.

**Comment by wouterkw** [comment]
Dag Mick,

Ik heb de hele sectie over SBB verwijderd (en daarmee ook de term begrippenkader) en heb aan het begin een stuk over terminologie toegevoegd om het geheel wat eenduidiger te maken.

Wouter
