### ISSUE TITLE
Naamgeving

### ISSUE THREAD

**Issue by EricOosterom** [nl-digigo/kadersinformatiemodellen#3]
Kleine puntjes: "RioNed" moet zijn "Stichting RIONED". 
En er wordt verwezen naar de toelichtende website van Stichting RIONED, maar wellicht is verwijzen naar https://data.gwsw.nl beter, daar is onze ontologie gepubliceerd. Allebei kan wellicht ook.

**Comment by wouterkw** [comment]
Dag Eric,

Dank voor je commentaar, ik heb het zojuist aangepast.

Wouter
